apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uku-gitops
  name: uku-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uku-gitops
  template:
    metadata:
      labels:
        app: uku-gitops
    spec:
      containers:
        - image: uku-gitops
          name: uku-gitops
          ports:
            - name: http
              containerPort: 8050
