apiVersion: v1
kind: Service
metadata:
  labels:
    app: uku-gitops
  name: uku-gitops
spec:
  ports:
    - name: http
      port: 8050
      targetPort: http
  selector:
    app: uku-gitops
  type: ClusterIP
